#
# Copyright 2015-2016 Red Hat, Inc. and/or its affiliates
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# export TRACING_SERVER=172.17.0.1
# docker-compose up

version: "2"

services:
  dropwizard:
    image: hawkular/apm-example-polyglot-zipkin-dropwizard
    extra_hosts:
      - "tracing-server:${TRACING_SERVER}"
    ports:
      - "3000:3000"
    environment:
      - TRACING_PORT
      - MAVEN_CONFIG=/home/app-user
  wildfy-swarm:
    image: hawkular/apm-example-polyglot-zipkin-wildfly-swarm
    extra_hosts:
      - "tracing-server:${TRACING_SERVER}"
    ports:
      - "3003:3003"
    environment:
      - TRACING_PORT
  js:
    image: hawkular/apm-example-polyglot-zipkin-js
    extra_hosts:
      - "tracing-server:${TRACING_SERVER}"
    ports:
      - "3001:3001"
    environment:
      - TRACING_PORT
  ruby:
    image: hawkular/apm-example-polyglot-zipkin-ruby
    extra_hosts:
      - "tracing-server:${TRACING_SERVER}"
    ports:
      - "3002:3002"
    environment:
      - TRACING_PORT
  cassandra:
    image: hawkular/apm-example-polyglot-zipkin-cassandra
    extra_hosts:
      - "tracing-server:${TRACING_SERVER}"
    environment:
      - JVM_OPTS=-Dcassandra.custom_tracing_class=com.thelastpickle.cassandra.tracing.ZipkinTracing -Dcassandra.custom_query_handler_class=org.apache.cassandra.cql3.CustomPayloadMirroringQueryHandler -DZipkinTracing.httpCollectorHost=tracing-server -DZipkinTracing.httpCollectorPort=${TRACING_PORT}
